language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - mvn clean install sonar:sonar
addons:
  sonarcloud:
    organization: "erudika"
    token:
      secure: "v+laBYW6JF9tyL4Oc0xPB41Kjde4JOUlfWqyUnungrj9bGTG2yOWTGeCUoQgGGYpdHzfTQMtD73Y0JaNDyQNqCcfsixqYORD9OvPcm6MPP/5+peBHbPoxRx6riqQfim/bX+dTtXJlDo6FX5iLRCVni4j8mF4wzGhYzlpTwiQ5YV+o9RGbke0y+mQcMnPfsC7BZU9oFuDBkDFv4QR2JofKD5iMbvxlzyKy9hW/hcpleQrXjHuhhUnSrUL1hKAHWS66X1UCsa6aTb0n8bOV6IqWjWsqwy5Gs9/5Op4pZx5rLRbkX9d8xWxgxbvKj759D6doCf7ymIyB05i1wSruWsdUgs6XaJmPHnN3IvqRlW5CEFxN5eDB1FDNBnJUkt+95Fd0YAIi9pt39JraBug8Vc9OBVc/m8qpasfamzKTPNKb+cLLIEKg7I3W69BHUUQgmCESGzqojrsWSNPUcorPg24a///J2+6ORJcO6501RH8DK5/ImVwf4z9QPXsoHY+0W48vExug6s3x7DGX2To73gABlGTYxrYvw+27/L1EF5hR2NgR6ZEo7Ar4cd/iPD2kc+IosSp7b92q/m3Zy9VgKmXzEWvOv3k4Q8hmUKw04djKWVBNO9U3GpGf/D4JqLMzX5/bV8sV+jAeXNdytvptTDqBid+JzGWJhGqs2M4OQY5Ivo="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/730c78c6f9b54f9cb959
    on_success: change
    on_failure: always
    on_start: never
    